include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_relative_imports: true
    always_put_required_named_parameters_first: true
    avoid_unnecessary_containers: true
    avoid_setters_without_getters: true
    file_names: true
    leading_newlines_in_multiline_strings: true
    prefer_contains: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    unnecessary_parenthesis: true
    use_decorated_box: true
    unreachable_from_main: true
    unnecessary_this: true
    use_enums: true
    use_function_type_syntax_for_parameters: true
    use_full_hex_values_for_flutter_colors: true
    discarded_futures: true
    empty_statements: true
    combinators_ordering: true
    unnecessary_breaks: true
    unnecessary_raw_strings: true
    secure_pubspec_urls: true
    implicit_call_tearoffs: true