name: propositional_analyzer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    fl_chart: ^0.65.0
    permission_handler: ^10.4.5
    path_provider: ^2.0.5
    flutter_svg: ^2.0.9
    flutter_riverpod: ^2.4.9
    shared_preferences: ^2.2.2
    adaptive_theme: ^3.4.0
    package_info_plus: ^4.1.1
    flutter_animated_dialog: ^2.0.1
    window_manager: ^0.3.7
    universal_platform: ^1.0.0+1
    app_settings: ^5.1.1
    url_launcher: ^6.2.2
    #http: ^1.1.2
    vector_math: ^2.1.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
    uses-material-design: true

    fonts:
        - family: Play
          fonts:
              - asset: assets/fonts/play/play.ttf
                style: normal
